### PR TITLE
CMake (Windows HID) and compiler updates

### PR DESCRIPTION
**Pull request by rpavlik**
Hopefully this will fix some of the "building with newer SDKs/compilers" stuff on Windows. I tested and was able to build with just vs2015 and the normal/full Windows 8.1 SDK (no WDK installed).

It's mostly CMake work in some modules shared with other projects, but there was also a warning fix - MSVC2015 actually has definitions for `isnan` and `isinf` in C mode, and they look potentially nicer, so we defer to those now on that compiler.

### CODE REVIEW

**Comment by janoc** [comment]
Hum, this fails to build on my Win10. 

CMake runs fine:
```
cmake .
-- The C compiler identification is MSVC 19.0.23918.0
-- The CXX compiler identification is MSVC 19.0.23918.0
-- Check for working C compiler using: Visual Studio 14 2015 Win64
-- Check for working C compiler using: Visual Studio 14 2015 Win64 -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler using: Visual Studio 14 2015 Win64
-- Check for working CXX compiler using: Visual Studio 14 2015 Win64 -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring WiiUse version 0.15.0
-- FindWindowsSDK: Detected Visual Studio 2012 or newer, not using the _xp toolset variant: including SDK versions that drop XP support in search!
-- Found WindowsSDK: C:/Program Files (x86)/Microsoft SDKs/Windows/v8.1A;C:/Program Files (x86)/Windows Kits/8.1;C:/Program Files (x86)/Microsoft SDKs/Windows/v8.0A;C:/Program Files (x86)/Windows Kits/8.0;C:/Program Files (x86)/Microsoft SDKs/Windows/v7.1A
-- Found WinHID: C:/Program Files (x86)/Windows Kits/8.1/lib/winv6.3/um/x64/hid.lib
-- Found WINHID_LIBRARY in the Windows SDK for Windows 8.1 , which may or may not affect minimum compatible Windows version.
-- Could NOT find SDL (missing:  SDL_LIBRARY SDL_INCLUDE_DIR)
-- Could NOT find GLUT (missing:  GLUT_glut_LIBRARY GLUT_INCLUDE_DIR)
-- Configuring done
-- Generating done
-- Build files have been written to: C:/R/Dependencies-x64-2015/wiiuse-dev/build
```

But then the build fails. API change?
```
Creating library C:/R/Dependencies-x64-2015/wiiuse-dev/build/src/Release/wiiuse.lib and object C:/R/Dependencies-x64-2015/wiiuse-dev/build/src/Release/wiiuse.exp
os_win.obj : error LNK2019: unresolved external symbol HidD_GetAttributes referenced in function wiiuse_os_find
os_win.obj : error LNK2019: unresolved external symbol HidD_GetHidGuid referenced in function wiiuse_os_find
os_win.obj : error LNK2019: unresolved external symbol HidD_SetOutputReport referenced in function wiiuse_os_write
C:\R\Dependencies-x64-2015\wiiuse-dev\build\src\Release\wiiuse.dll : fatal error LNK1120: 3 unresolved externals
```

**Comment by janoc** [comment]
I have now built from this branch again and it has compiled ok on Win10 and with MSVC 2015. However, there was a major cumulative update of both Win10 and MSVC 2015 in the meantime, so it is possible that the above issue was a Microsoft's problem which has been fixed since. 

So I guess this could be merged to master now.

**Comment by qwertychouskie** [comment]
> So I guess this could be merged to master now.

So why has this not been merged yet then? :)

**Comment by janoc** [comment]
You realize it is not my fix and my repo, right? I prefer to not stomp over Ryan's toes in these cases.

**Pull request closed without merging**
