### PR TITLE
Update CMake modules

### PR DESCRIPTION
**Pull request by rpavlik**
wasn't strictly necessary but it's nice to have. and I did it so may as well submit it

### CODE REVIEW

**Comment by janoc** [comment]
Thanks, looks good to me. 

Seems this doesn't build on ubuntu, though, you may want to update the dependency for Ubuntu to `libsdl1.2-dev` instead of `libsdl-dev` before we merge it.

**Comment by qwertychouskie** [comment]
> Seems this doesn't build on Ubuntu, though, you may want to update the CI dependency for Ubuntu to `libsdl1.2-dev` instead of `libsdl-dev` before we merge it.

Given how small the SDL example is, would it make more sense to just port it to SDL2?  I might give that a poke if no one else does.

**Comment by janoc** [comment]
Any PR would be welcome regarding porting the example. But I would prefer to have that as a separate PR and to at least temporarily fix the CI workflow file here - all it needs is updating the YAML file.

**Comment by rpavlik** [comment]
ok, let's see if this works.

**Comment by janoc** [comment]
And merged it.

**Pull request merged**
