### PR TITLE
ci windows mingw w64

### PR DESCRIPTION
**Pull request by jcelerier**
Continuation of #126

- WIP: mingw-w64 support
- Make it work on MinGW 64

### CODE REVIEW

**Comment by jcelerier** [comment]
with the current set of changes it seems to build here :-)

**Comment by jcelerier** [comment]
(tried from archlinux with this cmake toolchain file: https://gist.github.com/peterspackman/8cf73f7f12ba270aa8192d6911972fe8 and the mingw-w64-toolchain archlinux package)

**Comment by janoc** [comment]
Oof, are you actually cross-compiling? I am not sure that has ever been supported. Well, great that works but I assumed that we are talking about native MinGW compilation in Windows.

**Comment by janoc** [comment]
I also wonder how did it build for you because the CI build failed on this:

```
D:/a/wiiuse/wiiuse/src/wiiuse_internal.h:64:2: error: #error "Platform not yet supported!"
   64 | #error "Platform not yet supported!"
```
I guess that check needs to be adapted to support MinGW.

**Comment by jcelerier** [comment]
ah, I see why it fails - it builds with the cygwin API, while I'm using the "normal" mingw which uis just GCC or Clang targetting the Win32 API

**Comment by jcelerier** [comment]
looks like it works on the latest commit: https://github.com/jcelerier/wiiuse/actions/runs/2760902322 

tell me if that's ok for you and I'll remove the "enable ci on other branches" commit

**Comment by janoc** [comment]
> looks like it works on the latest commit: https://github.com/jcelerier/wiiuse/actions/runs/2760902322
Yep, it has passed now! Good job!

> tell me if that's ok for you and I'll remove the "enable ci on other branches" commit
Sure, no problem with that.

**Comment by janoc** [comment]
Let me know when you are done with this PR and I will then merge it. Thanks a lot for this contribution, having a working CI for platforms I don't use/have access to helps immensely.

**Comment by jcelerier** [comment]
i think it's good! thanks!

**Pull request merged**
